class AppTexts {
  static const Map<String, Map<String, String>> texts = {
    'en': {
      'app_name': 'LinkGuard',
      'app_subtitle': 'Automatic protection from dangerous links',
      'activate': 'Activate LinkGuard — تفعيل',
      'protection_is': 'Protection is',
      'you_are_protected': 'You are protected',
      'all_links_checked': 'All links are being checked automatically',
      'protection_active': 'Protection active',
      'tap_to_pause': 'Tap to pause',
      'safe_links_today': 'Safe links today',
      'threats_blocked': 'Threats blocked',
      'recent_checks': 'Recent checks',
      'home': 'Home',
      'history': 'History',
      'settings': 'Settings',
      'stats': 'Statistics',
      'scan': 'Scan',
      'link_history': 'Link History',
      'last_50': 'Last 50 links checked',
      'danger_title': 'Dangerous Link!',
      'danger_subtitle': 'رابط خطير! لا تكمل',
      'danger_body': 'This link is trying to steal your password or bank information. Do not open it.',
      'blocked_link': 'Blocked link',
      'threat_level': 'Threat level',
      'go_back': '← Go Back — العودة',
      'protection_section': 'PROTECTION',
      'link_protection': 'Link protection',
      'check_auto': 'Check all links automatically',
      'language_section': 'LANGUAGE — اللغة',
      'display_language': 'Display language',
      'appearance_section': 'APPEARANCE',
      'large_text': 'Large text mode',
      'large_text_sub': 'Bigger fonts for easier reading',
      'dark_mode': 'Dark mode',
      'dark_mode_sub': 'Easier on the eyes at night',
      'trusted_section': 'TRUSTED CONTACTS',
      'family_number': 'Trusted member numbers',
      'notify_family': 'Notify trusted members on danger',
      'notify_family_sub': 'Send SMS to all trusted members when dangerous link is detected',
      'add_trusted': 'Add number',
      'trusted_hint': 'e.g. +962 7X XXX XXXX',
      'no_trusted': 'No trusted members added yet',
      'step1_title': 'Enable Protection',
      'step1_sub': 'Press the activate button to start automatic link checking',
      'step2_title': 'Use your phone normally',
      'step2_sub': 'LinkGuard checks every link in WhatsApp, SMS, and email automatically',
      'step3_title': 'See warnings instantly',
      'step3_sub': 'If a link is dangerous, a clear warning appears before it opens',
      'safe_notif': 'Link is safe ✓',
      'safe_notif_body': 'This link has been verified and is safe to open.',
      'safe': 'SAFE',
      'danger': 'DANGER',
      'warn': 'WARN',
      'blocked': 'BLOCKED',
      'warning': 'WARNING',
      'manual_scan': 'Manual Link Scanner',
      'paste_link': 'Paste or type a link to check',
      'scan_now': 'Scan Now',
      'scanning': 'Scanning...',
      'result': 'Result',
      'whitelist': 'Trusted Websites',
      'whitelist_sub': 'These sites will never be blocked',
      'add_to_whitelist': 'Add trusted website',
      'whitelist_hint': 'e.g. google.com',
      'add': 'Add',
      'remove': 'Remove',
      'export_history': 'Export History',
      'export_sub': 'Save link history as CSV file',
      'export_done': 'History exported to Downloads ✓',
      'weekly_stats': 'Weekly Overview',
      'total_scanned': 'Total Scanned',
      'safe_rate': 'Safety Rate',
      'top_blocked': 'Most Blocked Domains',
      'no_data': 'No data yet',
      'clear_all': 'Clear All',
      'confirm_clear': 'Clear all history?',
      'confirm_clear_body': 'All entries will be deleted and cannot be undone.',
      'cancel': 'Cancel',
      'save': 'Save',
      'saved': 'Number saved ✓',
      'not_set': 'Not set yet',
      'select_all': 'Select All',
      'deselect_all': 'Deselect All',
      'delete': 'Delete',
      'selected': 'selected',
      'version': 'LinkGuard v1.0.0',
      'test_dangerous': 'Test Dangerous Link',
      'test_safe': 'Test Safe Link',
    },
    'ar': {
      'app_name': 'لينك غارد',
      'app_subtitle': 'حماية تلقائية من الروابط الخطرة',
      'activate': 'تفعيل LinkGuard — Activate',
      'protection_is': 'الحماية نشطة',
      'you_are_protected': 'أنت محمي',
      'all_links_checked': 'يتم فحص جميع الروابط تلقائياً',
      'protection_active': 'الحماية مفعّلة',
      'tap_to_pause': 'اضغط للإيقاف المؤقت',
      'safe_links_today': 'روابط آمنة اليوم',
      'threats_blocked': 'تهديدات محجوبة',
      'recent_checks': 'آخر عمليات الفحص',
      'home': 'الرئيسية',
      'history': 'السجل',
      'settings': 'الإعدادات',
      'stats': 'الإحصائيات',
      'scan': 'فحص',
      'link_history': 'سجل الروابط',
      'last_50': 'آخر 50 رابط تم فحصه',
      'danger_title': 'رابط خطير!',
      'danger_subtitle': 'Dangerous Link! Do not proceed',
      'danger_body': 'هذا الرابط يحاول سرقة كلمة مرورك أو معلوماتك المصرفية. لا تفتحه.',
      'blocked_link': 'الرابط المحجوب',
      'threat_level': 'مستوى الخطر',
      'go_back': 'العودة — Go Back →',
      'protection_section': 'الحماية',
      'link_protection': 'حماية الروابط',
      'check_auto': 'فحص جميع الروابط تلقائياً',
      'language_section': 'LANGUAGE — اللغة',
      'display_language': 'لغة العرض',
      'appearance_section': 'المظهر',
      'large_text': 'وضع النص الكبير',
      'large_text_sub': 'خطوط أكبر لقراءة أسهل',
      'dark_mode': 'الوضع الداكن',
      'dark_mode_sub': 'مريح للعيون في الليل',
      'trusted_section': 'جهات الاتصال الموثوقة',
      'family_number': 'أرقام الأعضاء الموثوقين',
      'notify_family': 'إشعار الأعضاء الموثوقين عند الخطر',
      'notify_family_sub': 'إرسال SMS لجميع الأعضاء عند اكتشاف رابط خطير',
      'add_trusted': 'إضافة رقم',
      'trusted_hint': 'مثال: 07X XXX XXXX+962',
      'no_trusted': 'لم تتم إضافة أعضاء موثوقين بعد',
      'step1_title': 'تفعيل الحماية',
      'step1_sub': 'اضغط على زر التفعيل لبدء فحص الروابط تلقائياً',
      'step2_title': 'استخدم هاتفك بشكل طبيعي',
      'step2_sub': 'LinkGuard يفحص كل رابط في واتساب والرسائل والبريد تلقائياً',
      'step3_title': 'رؤية التحذيرات فوراً',
      'step3_sub': 'إذا كان الرابط خطيراً، يظهر تحذير واضح قبل فتحه',
      'safe_notif': 'الرابط آمن ✓',
      'safe_notif_body': 'تم التحقق من هذا الرابط وهو آمن للفتح.',
      'safe': 'آمن',
      'danger': 'خطر',
      'warn': 'تحذير',
      'blocked': 'محجوب',
      'warning': 'تحذير',
      'manual_scan': 'فحص رابط يدوياً',
      'paste_link': 'الصق أو اكتب رابطاً للفحص',
      'scan_now': 'فحص الآن',
      'scanning': 'جارٍ الفحص...',
      'result': 'النتيجة',
      'whitelist': 'المواقع الموثوقة',
      'whitelist_sub': 'هذه المواقع لن تُحجب أبداً',
      'add_to_whitelist': 'أضف موقعاً موثوقاً',
      'whitelist_hint': 'مثال: google.com',
      'add': 'إضافة',
      'remove': 'حذف',
      'export_history': 'تصدير السجل',
      'export_sub': 'حفظ سجل الروابط كملف CSV',
      'export_done': 'تم التصدير إلى التنزيلات ✓',
      'weekly_stats': 'نظرة أسبوعية',
      'total_scanned': 'إجمالي الفحوصات',
      'safe_rate': 'نسبة الأمان',
      'top_blocked': 'أكثر النطاقات حجباً',
      'no_data': 'لا توجد بيانات بعد',
      'clear_all': 'مسح الكل',
      'confirm_clear': 'مسح السجل كامل؟',
      'confirm_clear_body': 'سيتم حذف جميع السجلات ولا يمكن التراجع.',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'saved': 'تم حفظ الرقم ✓',
      'not_set': 'لم يتم التعيين بعد',
      'select_all': 'تحديد الكل',
      'deselect_all': 'إلغاء تحديد الكل',
      'delete': 'حذف',
      'selected': 'محدد',
      'version': 'LinkGuard v1.0.0',
      'test_dangerous': 'اختبار رابط خطير',
      'test_safe': 'اختبار رابط آمن',
    },
  };

  static String get(String key, String lang) {
    return texts[lang]?[key] ?? texts['en']?[key] ?? key;
  }
}
